- include/bsp-android_ia.xml
Remove the old media driver vaapi on Celadon.
Jira: None
Test: None
Signed-off-by: Tianmi Chen <tianmi.chen@intel.com>
> [CELADON] Remove vaapi project

- include/bsp-android_ia.xml
trusty branches out omr1 branch for o/mr1 Celadon.
the patch switches the trusty branch to omr1 for Celadon omr1 manifest
Tracked-On: None
Signed-off-by: roger feng <roger.feng@intel.com>
> switch trusty branch to omr1 for o/mr1 Celadon

- include/bsp-celadon.xml
thermal-daemon is the proposed thermal solution for celadon.
Hence adding the source to the manifest.
Tracked-On: OAM-67241
Signed-off-by: ysiyer <yegnesh.s.iyer@intel.com>
> thermal-daemon: Add repo entry in manifest

- include/bsp-cic.xml
Tracked-On: OAM-89816
Change-Id: I7dd2b773a9971a83c9a1590a272119c334b40f2c
> [CIC] Migrate bsp/google diff patches to vendor/intel/utils

- include/aosp_vanilla.xml
Bug Fixed:
Bug: 144285917
Test: atest ActivityStackTests#testNavigateUpTo
Test: atest CtsSecurityTestCases:ActivityManagerTest# \
testActivityManager_attachNullApplication
Tracked-On : [OAM-91865](https://jira.devtools.intel.com/browse/OAM-91865)
Signed-off-by: svenate <salini.venate@intel.com>
> [CIC] Manifest changes to include CVE patches

- include/bsp-cic.xml
Support both OAM-92192 and CACTUS-16750
Tracked-On: CACTUS-16750
> Integrate iio-sensors-hal and safestringlib

- include/aosp_vanilla.xml
Tracked-On: OAM-96701
Signed-off-by: buildslave <ctbbot@intel.com>
> Update prebuilt Clang to r412851 (12.0.3)

- include/bsp-celadon.xml
Since we open sourced app icon manager into celadon git repo, so
we change the git address to new one accordingly.
Signed-off-by: Wan Shuang <shuang.wan@intel.com>
Traced-On: OAM-98236
> Include the open sourced app icon manager git tree.

- include/bsp-celadon.xml
This changes include MediaSDK C2 plugin on Android S,
together with oneVPL integration.
Change-Id: Ibd07596dc1276060131b1bc871bc975eef2bc3f3
Tracked-On: OAM-100096
Signed-off-by: Chen, Tianmi <tianmi.chen@intel.com>
> Integrate MediaSDK C2 plugin to Android S

- include/bsp-celadon.xml
removing it from source code
Tracked-On: OAM-100207
Signed-off-by: Aiswarya Cyriac <aiswarya.cyriac@intel.com>
> Hcitools are used only for debugging purpose and hence

- default.xml
- include/bsp-celadon.xml
Update lts2020-yocto remote, project and revision to
remote: https://github.com/intel
project: linux-intel-lts
revision: lts-v5.10.100-civ-android-220303T165800Z
Change-Id: I4013c41290917f4560584464428f01cc5d841f83
Tracked-On: OAM-101557
Signed-off-by: Badrappan, Jeevaka <jeevaka.badrappan@intel.com>
> Update lts2020-yocto remote and tag

- default.xml
- include/bsp-celadon.xml
Hcitools are used only for debugging purpose and hence
removing it from source code
Update lts2020-yocto remote, project and revision to
remote: https://github.com/intel
project: linux-intel-lts
revision: lts-v5.10.100-civ-android-220303T165800Z
Tracked-On: OAM-100206
Tracked-On: OAM-101403
Signed-off-by: Aiswarya Cyriac <aiswarya.cyriac@intel.com>
Signed-off-by: Badrappan, Jeevaka <jeevaka.badrappan@intel.com>
> Removed hcitools. Migrated yocto kernel

- include/aosp_vanilla.xml
- include/bsp-celadon.xml
Replace V4L2_codec2 in manifest with our own
under vendor/intel/external
Tracked-On: OAM-102557
Signed-off-by: Shaofeng Tang <shaofeng.tang@intel.com>
> Replace V4L2_codec2 with our own

- default.xml
- include/aosp_legacy.xml
- include/aosp_vanilla.xml
- include/bsp-celadon.xml
Test done : Boot check done
Tracked-On: OAM-112104
> Android Dessert Migration to Android 14 tag android-14.0.0_r2

- include/aosp_vanilla.xml
This patch will upgrade the AOSP tag for A14 to r17
Tests-Done: Build and boot android.
Tracked-On: OAM-114192
Change-Id: I8f16fab43f0eacb8d00361920586c35dbc4515a2
> Upgrade AOSP tag to r17

- include/aosp_vanilla.xml
This patch will upgrade the AOSP tag for A14 to r21
Tests-Done: Build and boot android successfully.
Tracked-On: OAM-114686
Change-Id: Idfe3c1788ad54ff08dbcd2cc58dbb94fbb214c4c
> Upgrade AOSP tag from r17 to r21

- include/bsp-celadon.xml
Updating the firmware revision to ensure proper functioning of Wi-Fi.
Tests done:
- Flashing and booting for CIV in GVT-d
- Enabling Wi-Fi and connecting to it
Change-Id: Ic7c7af952efe88a25e51deb546b8e6ecdfa082da
Tracked-On: OAM-115437
> Update the firmware revision to 20240115

- default.xml
- include/aosp_vanilla.xml
This patch will upgrade the AOSP tag from r21 to r24
Tests-Done: Build and boot android successfully.
Wi-Fi connected and working
app installation launch and run test done.
Tracked-On: OAM-115630
> Upgrade AOSP tag from r21 to r24

- include/bsp-celadon.xml
Removing the following unsupported kernels from manifest file:
- linux-intel-lts2021
- lts2021-chromium
Tests done:
- Android CIV
- Wi-Fi on/off/scan
- Bluetooth on/off/scan
- Camera capture/recording
- adb reboot
- adb remount in CIV
Tracked-On: OAM-125213
Change-Id: I55c8765aa27589532fd924ad021392d63e320f9d
> Removal of unused 5.15 kernel

- include/bsp-celadon.xml
Added linux-npu-driver for firmware.
Tests done:
- Android build
- Boot and verified npu device /dev/accel0 enumeration.
Tracked-On: OAM-126050
> Add linux-npu-driver
