default.xml, include/aosp_vanilla.xml
Jira: None
Test: Android Boots to homescreen
All features works fine
=> [CELADON] Updating manifest to O MR1 tag : android-8.1.0_r32

1, include/bsp-android_ia.xml
=> [CELADON] Add manifest for media sdk

include/bsp-celadon.xml
Tracked-On: CACTUS-14087
Signed-off-by: tao.w.wang@intel.com
=> Change "mediasdk" project name to "MediaSDK"

include/bsp-celadon.xml
Tracked-On: CACTUS-14094
Signed-off-by: tao.w.wang@intel.com
=> Add new repo kernel-modules

include/bsp-celadon.xml
repos under projectceladon
Tracked-On: None
Signed-off-by: Swaroop Balan <swaroop.balan@intel.com>
=> [CELADON] GFX staging repo are moved to the new

include/aosp_vanilla.xml
Tracked-On: None
Signed-off-by: Swaroop Balan <swaroop.balan@intel.com>
=> [CELADON] For CVE issue we need to update curl to master

include/bsp-celadon.xml
Tracked-On: OAM-69781
Signed-off-by: Swaroop Balan <swaroop.balan@intel.com>
=> [CELADON] Freezing the Firmware same as Internal Celadon

include/bsp-celadon.xml
Change-Id: I4f1c5f34f92d4a0364678e1f460c9a71d7a833fe
Tracked-On: OAM-71937
=> [CELADON] Adding manifest of MultiCamera epic

default.xml, include/aosp_vanilla.xml
Tracked-On: OAM-72113
Change-Id: I2c7c8cef13c2906fc5284b21736f4afacf2bfecd
Signed-off-by: rugnathr <rugnath.ram@intel.com>
Signed-off-by: Swaroop Balan <swaroop.balan@intel.com>
=> Update to android-9.0.0_r18

include/bsp-celadon.xml
Change-Id: Ib681828423c28330e0b9bdf59d3aad184125b1f3
Tracked-On: CACTUS-15024
Signed-off-by: Yihan He <yihan.he@intel.com>
=> Add https://github.com/intel/safestringlib into manifest of Celadon

default.xml, include/bsp-celadon.xml
Change-Id: I2ae805adc222f323979b1a315b554c663952bf10
Tracked-On: OAM-76132
Signed-off-by: Atul Vaish <atul.vaish@intel.com>
=> Manifest Changes for OPENVINO and NNHAL

default.xml, include/bsp-celadon.xml
Tracked-On: CACTUS-15568
Signed-off-by: wangtao <tao.w.wang@intel.com>
=> [Celadon] Update manifest for adding repo sync -c as default

default.xml, include/aosp_vanilla.xml
Tracked-On: OAM-84309
Signed-off-by: rugnathr <rugnath.ram@intel.com>
=> AOSP rebase tag android-9.0.0_r45

stable-build/ww201925_H.xml
=> [CLEADON] offical release 2019_WW25_H

include/bsp-celadon.xml
Tracked-On: CACTUS-16170
Signed-off-by: yinweix.wang@intel.com <yinweix.wang@intel.com>
=> [celadon_github] restore celadon-applications project

include/bsp-celadon.xml
=> [celadon_p] restore celadon-applications project

cic, include/bsp-cic.xml
Tracked-On: CACTUS-16169
Signed-off-by: jinhon1x <jinhongx.liu@intel.com>
=> New Github manifest for CIC in Celadon P

include/bsp-celadon.xml
Tracked-On: CACTUS-16187
Signed-off-by: yinweix.wang@intel.com <yinweix.wang@intel.com>
=> add OpenCL projects

include/bsp-celadon.xml
Tracked-On: CACTUS-16222
Signed-off-by: yinweix.wang@intel.com <yinweix.wang@intel.com>
=> add cic projects

include/bsp-celadon.xml
Tracked-On: CACTUS-16223
Signed-off-by: yinweix.wang@intel.com <yinweix.wang@intel.com>
=> rename hardware-intel-kernelflinger to kernelflinger

default.xml, include/aosp_vanilla.xml
Change-Id: I0bbd5c46917bbb9438b8161a7d3fbeee75a18050
Tracked-On: OAM-88235
=> Fetching android-9.0.0_r48 latest AOSP P tag

include/bsp-celadon.xml
Tracked-On: CACTUS-16291
Signed-off-by: jinhon1x <jinhongx.liu@intel.com>
=> [Celadon] Move mainline-tracking repo from r1 to r2

stable-build/ww201941_B.xml
Signed-off-by: Yihan He <yihan.he@intel.com>
=> [CELADON] offical release for 2019_WW41_B

include/bsp-celadon.xml
Signed-off-by: Zhong,Fangjian <fangjian.zhong@intel.com>
=> Add Trusty release binaries folder

include/bsp-cic.xml
Reverts projectceladon/manifest#80
=> Revert "Celadon/p/mr0/master"

include/bsp-cic.xml
Change-Id: I6cf62be43a5d61a27e9bdc9cfb66c0066724451d
Tracked-On: OAM-88599
Signed-off-by: tianmi.chen <tianmi.chen@intel.com>
=> Update media driver to include CML device support

include/bsp-cic.xml
Tracked-On: OAM-88620
Signed-off-by: JianFeng,Zhou <jianfeng.zhou@intel.com>
=> cic: Include projects needed for kernelflinger

stable-build/CIV_00.19.04.51_A10.xml
=> [CELADON] Manifest for WW51 external github upload

cic
=> AOSP rebase to android-9.0.0_r51 for cic

stable-build/CIV_01.20.04.02_A10.xml
=> [CELADON] Manifest added for CIV QMR0 Q4 Release

stable-build/CIC_00.19.04.20.03_A09.xml
=> [CIC] Add release manifest for CIC_00.19.04.20.03_A09 QE release

include/bsp-cic.xml
Reverts projectceladon/manifest#78
=> Revert "cic: Include projects needed for kernelflinger"

default.xml, include/aosp_vanilla.xml
=> Github aosp rebase to android-10.0.0_r25 on Q

include/bsp-cic.xml
This is a Merge of feature/p/mr0/mixins to
celadon/p/mr0/master
Tracked-On: OAM-88695
=> [CIC] Enable mixins for cic target

stable-build/ww202007.xml, stable-build/ww202008.xml
2020 ww07 and ww08
Tracked-On: OAM-89800
=> [CIC] Update stable weekly release manifest for

stable-build/CIV_00.20.01.09_A10.xml
=> [CELADON] February Manifest Release 2020

stable-build/CIC_00.20.01.08_A09.xml
=> [CIC] Add release manifest for CIC_00.20.01.08_A09 monthly release

include/bsp-celadon.xml
Tracked-On: OAM-89832
Signed-off-by: JianFeng,Zhou <jianfeng.zhou@intel.com>
=> remove project bootable/liveinstaller

include/bsp-celadon.xml
=> Removed the projects from manifest as they are no longer needed

include/bsp-celadon.xml
=> Removed the projects from manifests are they are no longer being used

include/aosp_vanilla.xml
=> prebuilt: Change revision of prebuilt to r365631

include/bsp-celadon.xml
Tracked-On: OAM-90364
Signed-off-by: JianFeng,Zhou <jianfeng.zhou@intel.com>
=> remove project vendor/intel/external/openssl

include/bsp-celadon.xml
=> [KBL PMR0][AOSP-Intel] Upgrade Python2 scripts in 'hardware/bsp/intel'

include/bsp-celadon.xml
=> [CELADON] Removal of Pystache

stable-build/CELADON_01.20.01.12_A09.xml
Signed-off-by: swaroop <swaroop.balan@intel.com>
=> [CELADON] Manifest added for PMR0 Platform Exit

stable-build/CIV_01.20.01.12_A10.xml
=> [CELADON] Manifest for CIV Platform Exit on KBL NUC

stable-build/CIC_01.20.01.12_A09.xml
=> [CIC] Add release manifest for CIC_01.20.01.12_A09 quarterly release

include/bsp-celadon.xml
=> manifest: Add kernel lts2019 project

stable-build/CIV_01.20.01.12_A10.xml
=> [CELADON] Remove vendor-intel-cic repo from the WW12 CIVmanifest

include/bsp-celadon.xml
Tracked-On: OAM-90603
Signed-off-by: Jingdong Lu <jingdong.lu@intel.com>
=> Remove log_infra from manifest

include/bsp-celadon.xml
=> Remove vendor-intel-cic since we met code match issues

include/bsp-celadon.xml
Tracked-On: OAM-90844
Signed-off-by: Zhong,Fangjian <fangjian.zhong@intel.com>
=> Remove trusty-ia source code repositories

cic
=> AOSP upgrade to android-9.0.0_r55 latest p tag on cic

default.xml, include/aosp_vanilla.xml
=> AOSP Upgrade to android-10.0.0_r33 latest AOSP Q tag

default.xml, include/celadon-manifest.xml
=> Added manifest project also to be included part of the manifest

stable-build/CIV_00.20.02.19_A10.xml
=> CIV manifest uploaded for Platform : CML NUC

include/bsp-cic.xml
=> Integrate 'metrics-discovery' lib

include/bsp-cic.xml
=> Disabling cic_dev target

stable-build/CIC_00.20.02.20_A09.xml
=> Adding CIC-CML release manifest for CIC_00.20.02.20_A09

include/bsp-celadon.xml
Change-Id: I3b47cb276925d4442c978817641b1592bf186e01
Tracked-On: OAM-91088
=> Added Thermal and Battery projects

include/bsp-celadon.xml
Add VM Manager project in manifest
Tracked-On: OAM-91114
Signed-off-by: Qi, Yadong <yadong.qi@intel.com>
=> Add VM Manager project

include/aosp_vanilla.xml, include/bsp-cic.xml
=> Updated external manifest to latest changes

cic, include/celadon-manifest.xml
=> Added Manifest project

cic
Update to the commit 62623d8 for external/aac which has
fixes for multiple overflow/runtime errors
Tracked-On: OAM-90419
Signed-off-by: akodanka <anoob.anto.kodankandath@intel.com>
Change-Id: I9f865973bc34641e1d567dc792f000ab7d75d0b8
=> Update external aac to fix overflow errors

include/bsp-cic.xml
Tracked-On: OAM-91154
Signed-off-by: Jingdong Lu <jingdong.lu@intel.com>
=> Add log_capture to CiC

default.xml
=> Added celadon_pmr0 native release manifest

include/bsp-celadon.xml
Remove VM Manager project from manifest
Tracked-On: OAM-91241
Signed-off-by: Qi, Yadong <yadong.qi@intel.com>
=> Remove VM Manager Project

include/bsp-celadon.xml
Tracked-On: OAM-91248
Signed-off-by: Babu B, Ramesh <ramesh.babu.b@intel.com>
=> Add Sensor Mediation in Manifest

include/bsp-celadon.xml
Tracked-On: OAM-91271
Signed-off-by: Babu B, Ramesh <ramesh.babu.b@intel.com>
=> Add Virtual Input Manager to Manifest

stable-build/CIV_00.20.02.23_A10.xml
=> Manifest added for CIV_00.20.02.23_A10 Release

stable-build/CIC_00.20.02.23_A09.xml
=> Adding CIC-CML release manifest for CIC_00.20.02.23_A09

stable-build/latest.xml, stable-build/test.xml
Change-Id: Ib2ee5d1fecc218823c783282991569eb537cb0bf
=> Added test.xml and pointing latest.xml to it

include/celadon-manifest.xml
Change-Id: I8f6fa29e24deeedf4cfb7d9e17520d2a2f954fe7
=> Modified manifest to be readonly as of now

stable-build/CIV_00.20.02.24_A10.xml, stable-build/latest.xml
=> Update Weekly External Release manifest

stable-build/CIC_00.20.02.24_A09.xml
=> Adding CIC-CML release manifest for CIC_00.20.02.24_A09

include/bsp-cic.xml
Change-Id: If98f7f10313c41b994b358b66a5026322d4835b9
Tracked-On: OAM-91677
Signed-off-by: Lakshmishree C <Lakshmishree C lakshmishree.c@intel.com>
=> Changes to enable NNHAL in CiC

include/bsp-cic.xml
=> Modified project to point to celadon/p/mr0/master branch

stable-build/CIC_00.20.03.31_A09.xml
=> Adding CIC-CML release manifest for CIC_00.20.03.31_A09

include/aosp_vanilla.xml
Bug Fixed:
Bug: 144285917
Test: atest ActivityStackTests#testNavigateUpTo
Test: atest CtsSecurityTestCases:ActivityManagerTest# \
testActivityManager_attachNullApplication
Tracked-On: [OAM-91944](https://jira.devtools.intel.com/browse/OAM-91944)
Signed-off-by: svenate <salini.venate@intel.com>
=> [CIV] Manifest changes to include CVE patches

include/bsp-celadon.xml
Change-Id: I5755d4801d2aa31156526408c3908d2664dcf72a
Tracked-On: OAM-92046
=> Change openvinto point to 2020.4 branch

include/aosp_vanilla.xml
Change-Id: I560b5bb64cda67b2f56f72b7123830f3b4e0ec77
Tracked-On: OAM-92804
=> Re-work "Rebase AOSP minigbm/drm_hwcomposer to latest"

default.xml, include/aosp_vanilla.xml, include/bsp-celadon.xml
Tracked-On: OAM-92853
Change-Id: I5e1326d729a57f0e41354d76431532df3a4ab70b
=> Google Public tag android-11.0.0_r3 is rebased

stable-build/CIC_01.20.03.36_A09.xml
Change-Id: I63455dfe4ec30de49d673ac01cb4dabf7694ea9c
=> Adding CIC-CML platform exit release manifest for CIC_01.20.03.36_A09

include/bsp-celadon.xml
This change is to help rebase libdrm on Android R
Change-Id: I449c6c519b820f471772e540d37bb13fb1d78f3d
Tracked-On: OAM-92960
Signed-off-by: Chenglei Ren <chenglei.ren@intel.com>
=> Rebase libdrm on Android R

include/bsp-celadon.xml
Change-Id: Ibde3eec33abedfb989acd87c522f5e1f92f26cda
Tracked-On: CACTUS-16809
=> Added oneDNN Project

default.xml, include/aosp_vanilla.xml
This changes is to update the public manifest files to align with aosp
r41 changes
Signed-off-by: jayanth1 <shankar.srinivas.jayanthi@intel.com>
=> update public manifest to align aosp r41

default.xml
=> AOSP rebase android-11.0.0_r17 done

default.xml, include/aosp_vanilla.xml
Tracked-On: OAM-95760
Signed-off-by: swaroopb swaroop.balan@intel.com
=> AOSP Rebase android-11.0.0_r27

default.xml, include/aosp_vanilla.xml
=> AOSP rebase to android-11.0.0_r33

include/bsp-celadon.xml
dldt and mkldnn latest code is merged to generic main branch.
Update the branch name in manifest
Tracked-On: OAM-96597
Signed-off-by: Jaikrishna Nemallapudi <nemallapudi.jaikrishna@intel.com>
=> Update dldt and mkldnn branch name

default.xml
Tracked-On: OAM-97046
Signed-off-by: "swaroopb <swaroop.balan@intel.com>"
=> AOSP rebase to r37 tag

include/bsp-celadon.xml
Tracked-On: CACTUS-16982
Signed-off-by: Nagamani Chennuboina <nagamani.chennuboina@intel.com>
=> Added oneTBB project to Android

default.xml, include/aosp_vanilla.xml
=> AOSP rebase to android-11.0.0_r38

default.xml
Change-Id: I7b1e47a0132e331e09cb07868ffba1a2b871abc2
Tracked-On: OAM-97932
=> AOSP rebase to r39 on master branch

include/bsp-celadon.xml
This is to help add hwc vhal to Android
Tracked-On: OAM-98085
Signed-off-by: Ren Chenglei <chenglei.ren@intel.com>
=> Add hwc vhal to manifest

include/bsp-celadon.xml
Add lts2020-yocto project
Tracked-On: OAM-98129
=> Add lts2020-yocto project

include/bsp-celadon.xml
Tracked-On: CACTUS-16301
Signed-off-by: wangtao <tao.w.wang@intel.com>
=> dd hcitools project to celadon opensource

default.xml, include/aosp_vanilla.xml
=> AOSP rebase android-12.0.0_r11 on Master branch

default.xml, include/aosp_vanilla.xml
=> AOSP rebase to r26 tag is done

include/bsp-celadon.xml
Change-Id: I134c6d75f71b780391cbfe29e818e9d0888aa1ae
Tracked-On: OAM-98190
Signed-off-by: Nagamani Chennuboina <nagamani.chennuboina@intel.com>
=> Removing NN-Hal

include/bsp-celadon.xml
Change evmm point to master branch
Tracked-On: OAM-100994
Signed-off-by: Yadong Qi <yadong.qi@intel.com>
=> Change BSP:evmm point to master branch

default.xml
Signed-off-by: svenate <salini.venate@intel.com>
=>  AOSP rebase to r46 on R-Stable branch

default.xml, include/aosp_vanilla.xml
=> Aosp rebase android-12.0.0_r28 on master branch

.github/workflows/Runchecks.yaml
=> Added .github actions to do basic checks

include/bsp-celadon.xml
Tracked-On: OAM-101826
Signed-off-by: Deepa G K <g.k.deepa@intel.com>
=> Include camera-vhal to bsp manifest on master

include/aosp_vanilla.xml, include/bsp-celadon.xml
Change-Id: I81f9b72a46cccccb22af104269362e7345afb58f
Tracked-On: OAM-102740
Signed-off-by: Liu, Yuanzhe <yuanzhe.liu@intel.com>
=> disable external/drm_hwcomposer and move it under vendor folder.

include/bsp-celadon.xml, include/celadon-manifest.xml
=> Made changes to sync from celadon/s/mr0/stable branch

default.xml, include/aosp_vanilla.xml, include/bsp-celadon.xml
=> Manifest upgraded to Android T android-13.0.0_r1

include/bsp-celadon.xml
=> Updated lts2020-chromium to point to main branch

include/bsp-celadon.xml
Change-Id: I5d17a63d9001bcd13218693721706b534cc67634
Tracked-On: OAM-103397
=> Add kernel 5.15 project

include/bsp-celadon.xml
Add vm-manager-binaries in manifest
Tracked-On: OAM-103893
Signed-off-by: Yadong Qi <yadong.qi@intel.com>
=> Add vm-manager-binaries in manifest

default.xml, include/aosp_vanilla.xml
=> Aosp rebase android-13.0.0_r4 on master branch

stable-build/CIV_03.22.03.37_A11.xml
=> Added CIV_03.22.03.37_A11 manifest release.

default.xml, include/aosp_vanilla.xml
=> AOSP rebase to android-13.0.0_r12

include/bsp-celadon.xml
adding new tag lts-v5.15.74-20221108-r1
=> update manifest for kernel-5.15.74 rebase

include/bsp-celadon.xml
Tracked-On: OAM-104870
Signed-off-by: Shweta Joshi <shweta.joshi@intel.com>
=> Change branch to main for linux-intel-lts2021-chromium

include/bsp-celadon.xml
Checking out clipboard-agent to vendor/intel/external
Tracked-On: OAM-104916
=> Checking out clipboard-agent to vendor/intel/external

include/bsp-celadon.xml
=> Remove not supported kernels

default.xml, include/nnhal-manifest.xml
Created an xml file for adding nn-hal dependencies and included it in r1, r2 manifest.
Change-Id: I22047a38003e3384a85cb9a48b82f6045fcc347c
Tracked-On: OAM-105821
Signed-off-by: Anoob Anto K <anoob.anto.kodankandath@intel.com>
Signed-off-by: Ratnesh Kumar Rai <ratnesh.kumar.rai@intel.com>
=> Adding nn-hal dependencies to manifest

default.xml, include/aosp_vanilla.xml
Change-Id: Iff3215b17f6c0c0cfab4288538aeff9f7229a982
Tracked-On: OAM-105487
=> Upgrade AOSP T Tag to 13.0.0_r30

include/nnhal-manifest.xml
=> Updated remote, version info for openvino 2022.3.0 and its dependencies

include/bsp-celadon.xml
=> Remove vm-manager project from manifest

include/bsp-celadon.xml
=> Removed device-intel-cic since its not used

include/bsp-celadon.xml
=> Removing aaf since aafd daemon is disabled

default.xml, include/aosp_vanilla.xml
updating aosp manifest from android-13.0.0_r43 to android-13.0.0_r43
Tracked-On: OAM-110529
=> Upgrading AOSP to New Version android-13.0.0_r43

include/bsp-celadon.xml
Tests Done: Build and boot
Tracked-On: OAM-126776 Change-Id: I70c24923888b5aa82b88366d0bc873933ef35f4b
Signed-off-by: Ravi Kumar Soni <ravi.kumar.soni@intel.com>
=> Add oneapi-integration project

include/bsp-celadon.xml
Coverity issue : remove safestringlib
Tracked-On: OAM-131029
Change-Id: Id8abd475c0da6f52309317bb91cfb1c9d0599289
=> Coverity issue : remove safestringlib
